name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Tests (JUnit + Cucumber)
        run: mvn -B -ntp clean verify -Dcucumber.plugin="pretty,html:target/cucumber-report.html,json:target/cucumber.json"

      - name: Publicar reporte Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: |
            target/cucumber-report.html
            target/cucumber.json